# import json

# with open('currency_exchange_data.json', 'r') as file:
#     currency_data = json.load(file)

# # print(currency_data)

# # print(type(currency_data))

# for key in currency_data['rates'].keys():
#     print(key)






# currency_list = ["AGLD", "FJD", "LVL", "SCR", "BBD", "HNL", "UGX", "KUJI", "NEAR", "AIOZ", "AUDIO", "WLD", "HNT", "ETHFI", "FARM", "SDG", "DGB", "BCH", "AI", "FKP", "JST", "HOT", "AR", "SEI", "QAI", "SEK", "BB", "QAR", "JTO", "WEMIX", "G", "FLR", "BIGTIME", "BDT", "T", "LYD", "W", "BDX", "BABYDOGE", "SFP", "DIA", "PORK", "JUP", "RSS3", "LYX", "SGB", "SGD", "STRD", "WOO", "BLUR", "STRK", "WZRD", "HRK", "DJF", "OMIKAMI", "WAVES", "FLOKI", "SHP", "BGB", "SAND", "DKK", "WCFG", "QUBIC", "BGN", "UMA", "FOX", "WSTETH", "TUSD", "LRDS", "HTG", "BHD", "OAS", "COVAL", "ZETACHAIN", "CGLD", "UNI", "FX", "HUF", "BIF", "GF", "PEPECOIN", "WELL", "SWFTC", "BIT", "GT", "SKK", "SKL", "UOS", "WST", "SHPING", "BRETT", "MYTH", "DNT", "HT", "TRUAPT", "SLE", "FLOW", "UPI", "SLL", "SLP", "ID", "DOG", "GIGA", "DOP", "IO", "UQC", "IQ", "DOT", "OSAK", "1INCH", "MAD", "FNSA", "TURBO", "BLD", "UNFI", "APEX", "FTM", "EVER", "POWR", "FTN", "MAV", "CORGIAI", "FTW", "ARKM", "ATOM", "SAVAX", "QUICK", "PENDLE", "BLZ", "BOBA", "TONE", "BMD", "SNT", "SNX", "USD", "API3", "ROSE", "SATS", "PORTAL", "SOL", "MUMU", "SOS", "BNB", "OGN", "UST", "CELR", "BND", "CELO", "TBTC", "AUCTION", "MANTA", "BADGER", "MULTI", "AERO", "SPA", "BNT", "SHDW", "BOB", "MDL", "OHM", "MDT", "ANDY", "AERGO", "KOIN", "MX", "EGLD", "KAS", "TRUMP", "MEW", "PUNDIX", "FXS", "AEVO", "SRD", "NU", "FLUX", "TOPIA", "BPX", "QNT", "OM", "ETHW", "MUSE", "ETHX", "OP", "CANTO", "MGA", "OKB", "WETH", "SSP", "JUPSOL", "NEON", "SSV", "OKT", "ETH2", "PAAL", "KCS", "BUSD", "ARPA", "BRL", "ALCX", "ALEX", "STD", "STG", "IOTX", "SHIB", "KDA", "ZAR", "ALEO", "STN", "BSD", "STX", "QI", "CAIR", "ZBC", "BLAST", "BSV", "IOST", "SUI", "CAKE", "MSOL", "OMG", "OMI", "PYUSD", "SUN", "BTC", "UYU", "IOTA", "ZYPTO", "BTG", "OMR", "MIR", "KES", "BTN", "RONIN", "SOLVBTC", "SVC", "BTT", "ONE", "RENDER", "ONG", "CETH", "ANKR", "ALGO", "SYLO", "UZS", "SC", "SD", "ONT", "DYM", "DYP", "MKD", "DZD", "MKR", "KGS", "ICP", "ZEC", "XAF", "NEST", "ICX", "XAG", "KMNO", "XAI", "ZEN", "FRIEND", "DOGE", "SXP", "HBAR", "XAU", "MLN", "PEPE", "KHR", "IDR", "DOGS", "XBC", "CTSI", "BWP", "COMAI", "OUSG", "C98", "OSMO", "NTRN", "SYN", "MMK", "SYP", "CRPT", "GAJ", "GAL", "GAS", "XCD", "MMX", "BOME", "VR", "XCH", "SYNC", "CBBTC", "THETA", "PANDORA", "XCN", "SZL", "ORN", "NEXO", "AAVE", "MNT", "GBP", "BONK", "BYN", "XDC", "PERP", "BYR", "BONE", "BOND", "MOG", "XDR", "TIME", "BICO", "BZD", "MOP", "MONA", "HMSTR", "XEC", "PEOPLE", "XT", "ZIL", "XEM", "WEETH", "TRAC", "MPL", "10SET", "WAXL", "OOKI", "BORA", "KMF", "GEL", "ZK", "RSETH", "EETH", "KNC", "PROM", "ALEPH", "PONKE", "BODEN", "GFI", "MRO", "MRS", "MRU", "BORG", "SUPEROETHB", "WAXP", "SUKU", "GGP", "GRIN", "VEF", "BTRFLY", "ZMK", "KARRAT", "ALPH", "MOBILE", "TAO", "MTL", "VET", "VES", "ZMW", "USDT", "USDC.E", "OXT", "USDP", "ILS", "ILV", "GHS", "KPW", "USDY", "EDU", "MEDIA", "KEEP", "CAD", "CAF", "EEK", "MUR", "IMP", "USD0", "GIP", "BEAM", "IMX", "CAT", "USDE", "USDD", "USDC", "USDB", "XMON", "RETH", "INJ", "KRL", "VGX", "CHEX", "MVR", "TRIBE", "INR", "INV", "KRW", "STSOL", "MWC", "XLM", "DORA", "MWK", "EIGEN", "SUPER", "KSM", "RNDR", "GALA", "EGP", "RAD", "MXC", "TEL", "MOVR", "RAI", "XMR", "MXN", "TET", "MCOIN", "CDF", "GLM", "RAY", "BTC.B", "CDT", "FDUSD", "ZRO", "KUB", "NPXS", "IQD", "GMD", "RBN", "ZRX", "MYR", "CEL", "XOF", "GMT", "BEER", "SWETH", "CET", "GMX", "OMNI", "GNF", "MZN", "CFG", "IRR", "GNO", "GNT", "GNS", "XPD", "THB", "XPF", "VANRY", "ABT", "CFX", "CDAI", "KWD", "VELO", "XPT", "ISK", "ACH", "MINA", "TIA", "VTHO", "PAB", "ACS", "ACX", "REI", "REN", "ELA", "REP", "ADA", "ELF", "REQ", "STORJ", "CHF", "RARI", "ELG", "ULTIMA", "RARE", "LADYS", "PAXG", "PAX", "XRD", "CHR", "VND", "$WEN", "CHZ", "KYD", "XRP", "JASMY", "INDEX", "TJS", "AED", "FIDA", "H2O", "EML", "ZWD", "OCEAN", "QGOLD", "ZWL", "PCI", "ENA", "RGT", "ENJ", "TKX", "KZT", "YFII", "DIMO", "GRT", "HBTC", "AFN", "TFUEL", "ENS", "DEGEN", "CKB", "LUNC", "XTZ", "LUNA", "AURORA", "AGI", "EOS", "GST", "FORT", "RIF", "NAD", "FRXETH", "TMM", "SLERF", "GTC", "PEN", "TMT", "CLF", "TOSHI", "EUROC", "SUNDOG", "GTQ", "CLP", "TND", "CLV", "$MYRO", "XVS", "MEME", "LYXE", "SFUND", "TON", "TOP", "PGK", "TOR", "GYEN", "CNH", "NCT", "WLUNA", "ERN", "VENOM", "VOXEL", "RLC", "RLB", "MAGA", "CNY", "PHP", "RLY", "OX_OLD", "COQ", "COP", "HOPR", "AKT", "COW", "GLMR", "ORAI", "XYO", "ETB", "GXC", "ETC", "VUV", "LAK", "ETH", "NEO", "KLAY", "MEMES", "ALL", "MAVIA", "HIGH", "TRB", "ALT", "ORDI", "GYD", "TRU", "AMD", "DREP", "ETHDYDX", "TRY", "LBP", "TRX", "NFT", "EUR", "AMP", "ORCA", "CQT", "USTC", "RON", "NGN", "CRC", "PKR", "CRE", "LUSD", "ANG", "SPELL", "LCX", "CRO", "PLA", "TTD", "SFRXETH", "CRV", "MNDE", "ANT", "BAKE", "RPL", "AOA", "PLN", "AZERO", "LDO", "MAGIC", "ALICE", "CORECHAIN", "PLU", "SEAM", "CTC", "NIO", "APE", "LEO", "APL", "MCO2", "00", "MATIC", "APT", "APU", "CTX", "PNG", "TVK", "CUC", "PYTH", "CUP", "TWD", "RSD", "FRAX", "VRSC", "WBETH", "METH", "BAND", "POL", "ASTR", "NKN", "RSR", "TWT", "ARB", "CVC", "VARA", "CVE", "ARK", "LOKA", "ARS", "CVX", "LBTC", "MPLX", "SUSHI", "WBTC", "ASM", "RUB", "AST", "MANA", "CSPR", "ATA", "NMR", "JEP", "NMT", "ATH", "LIT", "TNSR", "POLYX", "DESO", "LOOM", "RVN", "PRO", "TZS", "PRQ", "ONDO", "AUD", "RWF", "KAVA", "NOK", "STRAX", "LKR", "NOT", "NOS", "CZK", "AVT", "NPC", "EURC", "YER", "LSETH", "MASK", "AWG", "NPR", "PRIME", "YFI", "MOODENG", "CWBTC", "POPCAT", "WBT", "LQTY", "OLAS", "ALUSD", "PUPS", "PIXEL", "ZETA", "AXL", "BILLY", "CHEEL", "YGG", "AXS", "HONEY", "0X0", "COMP", "HFT", "WAMPL", "RUNE", "DEXT", "FORTH", "GHST", "MATH", "IDEX", "DEXE", "VNST", "AVAX", "AZN", "AMPL", "UAH", "BANANA", "NEIRO", "LPT", "EZETH", "GODS", "EDUM", "PYG", "JMD", "XAUT", "PYR", "BTRST", "MKUSD", "DAG", "DAI", "DAO", "AVAIL", "DAR", "FET", "CBETH", "LRC", "REPV2", "LRD", "CORE", "DASH", "POKT", "SAGA", "LSD", "JOD", "GUSD", "HKD", "JOE", "ARSMEP", "LSL", "LSK", "SAFE", "RDOG", "DCR", "WIF", "LTC", "METIS", "ECOIN", "STETH", "NXM", "LTL", "SAR", "DYDX", "AGIX", "MUBI", "POND", "JPY", "SBD", "DDX", "LINK", "QTUM", "WILD", "POLS", "FIL", "POLY", "BAL", "BAM", "FIS", "BAT", "NZD", "COTI"]

# for item in currency_list:
#     print('<option value="' + item + '">' + item + '</option>')





import json, requests

print(requests.get('https://api.currencyfreaks.com/v2.0/rates/latest?apikey=f995675724b34c49ad4de85dc9867075').json())





# AGLD
# FJD
# LVL
# SCR
# BBD
# HNL
# UGX
# KUJI
# NEAR
# AIOZ
# AUDIO
# WLD
# HNT
# ETHFI
# FARM
# SDG
# DGB
# BCH
# AI
# FKP
# JST
# HOT
# AR
# SEI
# QAI
# SEK
# BB
# QAR
# JTO
# WEMIX
# G
# FLR
# BIGTIME
# BDT
# T
# LYD
# W
# BDX
# BABYDOGE
# SFP
# DIA
# PORK
# JUP
# RSS3
# LYX
# SGB
# SGD
# STRD
# WOO
# BLUR
# STRK
# WZRD
# HRK
# DJF
# OMIKAMI
# WAVES
# FLOKI
# SHP
# BGB
# SAND
# DKK
# WCFG
# QUBIC
# BGN
# UMA
# FOX
# WSTETH
# TUSD
# LRDS
# HTG
# BHD
# OAS
# COVAL
# ZETACHAIN
# CGLD
# UNI
# FX
# HUF
# BIF
# GF
# PEPECOIN
# WELL
# SWFTC
# BIT
# GT
# SKK
# SKL
# UOS
# WST
# SHPING
# BRETT
# MYTH
# DNT
# HT
# TRUAPT
# SLE
# FLOW
# UPI
# SLL
# SLP
# ID
# DOG
# GIGA
# DOP
# IO
# UQC
# IQ
# DOT
# OSAK
# 1INCH
# MAD
# FNSA
# TURBO
# BLD
# UNFI
# APEX
# FTM
# EVER
# POWR
# FTN
# MAV
# CORGIAI
# FTW
# ARKM
# ATOM
# SAVAX
# QUICK
# PENDLE
# BLZ
# BOBA
# TONE
# BMD
# SNT
# SNX
# USD
# API3
# ROSE
# SATS
# PORTAL
# SOL
# MUMU
# SOS
# BNB
# OGN
# UST
# CELR
# BND
# CELO
# TBTC
# AUCTION
# MANTA
# BADGER
# MULTI
# AERO
# SPA
# BNT
# SHDW
# BOB
# MDL
# OHM
# MDT
# ANDY
# AERGO
# KOIN
# MX
# EGLD
# KAS
# TRUMP
# MEW
# PUNDIX
# FXS
# AEVO
# SRD
# NU
# FLUX
# TOPIA
# BPX
# QNT
# OM
# ETHW
# MUSE
# ETHX
# OP
# CANTO
# MGA
# OKB
# WETH
# SSP
# JUPSOL
# NEON
# SSV
# OKT
# ETH2
# PAAL
# KCS
# BUSD
# ARPA
# BRL
# ALCX
# ALEX
# STD
# STG
# IOTX
# SHIB
# KDA
# ZAR
# ALEO
# STN
# BSD
# STX
# QI
# CAIR
# ZBC
# BLAST
# BSV
# IOST
# SUI
# CAKE
# MSOL
# OMG
# OMI
# PYUSD
# SUN
# BTC
# UYU
# IOTA
# ZYPTO
# BTG
# OMR
# MIR
# KES
# BTN
# RONIN
# SOLVBTC
# SVC
# BTT
# ONE
# RENDER
# ONG
# CETH
# ANKR
# ALGO
# SYLO
# UZS
# SC
# SD
# ONT
# DYM
# DYP
# MKD
# DZD
# MKR
# KGS
# ICP
# ZEC
# XAF
# NEST
# ICX
# XAG
# KMNO
# XAI
# ZEN
# FRIEND
# DOGE
# SXP
# HBAR
# XAU
# MLN
# PEPE
# KHR
# IDR
# DOGS
# XBC
# CTSI
# BWP
# COMAI
# OUSG
# C98
# OSMO
# NTRN
# SYN
# MMK
# SYP
# CRPT
# GAJ
# GAL
# GAS
# XCD
# MMX
# BOME
# VR
# XCH
# SYNC
# CBBTC
# THETA
# PANDORA
# XCN
# SZL
# ORN
# NEXO
# AAVE
# MNT
# GBP
# BONK
# BYN
# XDC
# PERP
# BYR
# BONE
# BOND
# MOG
# XDR
# TIME
# BICO
# BZD
# MOP
# MONA
# HMSTR
# XEC
# PEOPLE
# XT
# ZIL
# XEM
# WEETH
# TRAC
# MPL
# 10SET
# WAXL
# OOKI
# BORA
# KMF
# GEL
# ZK
# RSETH
# EETH
# KNC
# PROM
# ALEPH
# PONKE
# BODEN
# GFI
# MRO
# MRS
# MRU
# BORG
# SUPEROETHB
# WAXP
# SUKU
# GGP
# GRIN
# VEF
# BTRFLY
# ZMK
# KARRAT
# ALPH
# MOBILE
# TAO
# MTL
# VET
# VES
# ZMW
# USDT
# USDC.E
# OXT
# USDP
# ILS
# ILV
# GHS
# KPW
# USDY
# EDU
# MEDIA
# KEEP
# CAD
# CAF
# EEK
# MUR
# IMP
# USD0
# GIP
# BEAM
# IMX
# CAT
# USDE
# USDD
# USDC
# USDB
# XMON
# RETH
# INJ
# KRL
# VGX
# CHEX
# MVR
# TRIBE
# INR
# INV
# KRW
# STSOL
# MWC
# XLM
# DORA
# MWK
# EIGEN
# SUPER
# KSM
# RNDR
# GALA
# EGP
# RAD
# MXC
# TEL
# MOVR
# RAI
# XMR
# MXN
# TET
# MCOIN
# CDF
# GLM
# RAY
# BTC.B
# CDT
# FDUSD
# ZRO
# KUB
# NPXS
# IQD
# GMD
# RBN
# ZRX
# MYR
# CEL
# XOF
# GMT
# BEER
# SWETH
# CET
# GMX
# OMNI
# GNF
# MZN
# CFG
# IRR
# GNO
# GNT
# GNS
# XPD
# THB
# XPF
# VANRY
# ABT
# CFX
# CDAI
# KWD
# VELO
# XPT
# ISK
# ACH
# MINA
# TIA
# VTHO
# PAB
# ACS
# ACX
# REI
# REN
# ELA
# REP
# ADA
# ELF
# REQ
# STORJ
# CHF
# RARI
# ELG
# ULTIMA
# RARE
# LADYS
# PAXG
# PAX
# XRD
# CHR
# VND
# $WEN
# CHZ
# KYD
# XRP
# JASMY
# INDEX
# TJS
# AED
# FIDA
# H2O
# EML
# ZWD
# OCEAN
# QGOLD
# ZWL
# PCI
# ENA
# RGT
# ENJ
# TKX
# KZT
# YFII
# DIMO
# GRT
# HBTC
# AFN
# TFUEL
# ENS
# DEGEN
# CKB
# LUNC
# XTZ
# LUNA
# AURORA
# AGI
# EOS
# GST
# FORT
# RIF
# NAD
# FRXETH
# TMM
# SLERF
# GTC
# PEN
# TMT
# CLF
# TOSHI
# EUROC
# SUNDOG
# GTQ
# CLP
# TND
# CLV
# $MYRO
# XVS
# MEME
# LYXE
# SFUND
# TON
# TOP
# PGK
# TOR
# GYEN
# CNH
# NCT
# WLUNA
# ERN
# VENOM
# VOXEL
# RLC
# RLB
# MAGA
# CNY
# PHP
# RLY
# OX_OLD
# COQ
# COP
# HOPR
# AKT
# COW
# GLMR
# ORAI
# XYO
# ETB
# GXC
# ETC
# VUV
# LAK
# ETH
# NEO
# KLAY
# MEMES
# ALL
# MAVIA
# HIGH
# TRB
# ALT
# ORDI
# GYD
# TRU
# AMD
# DREP
# ETHDYDX
# TRY
# LBP
# TRX
# NFT
# EUR
# AMP
# ORCA
# CQT
# USTC
# RON
# NGN
# CRC
# PKR
# CRE
# LUSD
# ANG
# SPELL
# LCX
# CRO
# PLA
# TTD
# SFRXETH
# CRV
# MNDE
# ANT
# BAKE
# RPL
# AOA
# PLN
# AZERO
# LDO
# MAGIC
# ALICE
# CORECHAIN
# PLU
# SEAM
# CTC
# NIO
# APE
# LEO
# APL
# MCO2
# 00
# MATIC
# APT
# APU
# CTX
# PNG
# TVK
# CUC
# PYTH
# CUP
# TWD
# RSD
# FRAX
# VRSC
# WBETH
# METH
# BAND
# POL
# ASTR
# NKN
# RSR
# TWT
# ARB
# CVC
# VARA
# CVE
# ARK
# LOKA
# ARS
# CVX
# LBTC
# MPLX
# SUSHI
# WBTC
# ASM
# RUB
# AST
# MANA
# CSPR
# ATA
# NMR
# JEP
# NMT
# ATH
# LIT
# TNSR
# POLYX
# DESO
# LOOM
# RVN
# PRO
# TZS
# PRQ
# ONDO
# AUD
# RWF
# KAVA
# NOK
# STRAX
# LKR
# NOT
# NOS
# CZK
# AVT
# NPC
# EURC
# YER
# LSETH
# MASK
# AWG
# NPR
# PRIME
# YFI
# MOODENG
# CWBTC
# POPCAT
# WBT
# LQTY
# OLAS
# ALUSD
# PUPS
# PIXEL
# ZETA
# AXL
# BILLY
# CHEEL
# YGG
# AXS
# HONEY
# 0X0
# COMP
# HFT
# WAMPL
# RUNE
# DEXT
# FORTH
# GHST
# MATH
# IDEX
# DEXE
# VNST
# AVAX
# AZN
# AMPL
# UAH
# BANANA
# NEIRO
# LPT
# EZETH
# GODS
# EDUM
# PYG
# JMD
# XAUT
# PYR
# BTRST
# MKUSD
# DAG
# DAI
# DAO
# AVAIL
# DAR
# FET
# CBETH
# LRC
# REPV2
# LRD
# CORE
# DASH
# POKT
# SAGA
# LSD
# JOD
# GUSD
# HKD
# JOE
# ARSMEP
# LSL
# LSK
# SAFE
# RDOG
# DCR
# WIF
# LTC
# METIS
# ECOIN
# STETH
# NXM
# LTL
# SAR
# DYDX
# AGIX
# MUBI
# POND
# JPY
# SBD
# DDX
# LINK
# QTUM
# WILD
# POLS
# FIL
# POLY
# BAL
# BAM
# FIS
# BAT
# NZD
# COTI
